In [1]:
import numpy as np
from PIL import Image
import os
import cv2

In [17]:
data = []
labels = []

cats=os.listdir("C:\\Users\\win_10\\Desktop\\Final Project\\animals\\cats")
for cat in cats:
    imag=cv2.imread("C:\\Users\\win_10\\Desktop\\Final Project\\animals\\cats\\"+cat)
    cat_array = np.asarray(imag)
    img_from_ar = Image.fromarray(cat_array, 'RGB')
    resized_image = img_from_ar.resize((50, 50))
    data.append(np.array(resized_image))
    labels.append(0)
    

In [23]:
bats=os.listdir("C:\\Users\\win_10\\Desktop\\Final Project\\animals\\bats")
for bat in bats:
    imag=cv2.imread("C:\\Users\\win_10\\Desktop\\Final Project\\animals\\bats\\"+bat)
    bat_array = np.asarray(imag)
    img_from_ar = Image.fromarray(bat_array, 'RGB')
    resized_image = img_from_ar.resize((50, 50))
    data.append(np.array(resized_image))
    labels.append(1)

spiders=os.listdir("C:\\Users\\win_10\\Desktop\\Final Project\\animals\\spiders")
for spider in spiders:
    imag=cv2.imread("C:\\Users\\win_10\\Desktop\\Final Project\\animals\\spiders\\"+spider)
    sp_array = np.asarray(imag)
    img_from_ar = Image.fromarray(sp_array, 'RGB')
    resized_image = img_from_ar.resize((50, 50))
    data.append(np.array(resized_image))
    labels.append(2)
    
wolverines=os.listdir("C:\\Users\\win_10\\Desktop\\Final Project\\animals\\wolverines")
for wolverine in wolverines:
#     print(wolverine)
    ab=cv2.imread("C:\\Users\\win_10\\Desktop\\Final Project\\animals\\wolverines\\"+wolverine)
    wolv_array = np.asarray(ab)
    img_from_ar = Image.fromarray(wolv_array, 'RGB')
    resized_image = img_from_ar.resize((50, 50))
    data.append(np.array(resized_image))
    labels.append(3)
    

In [24]:
animals=np.array(data)
labels=np.array(labels)

In [25]:
np.save("animals",animals)
np.save("labels",labels)

In [26]:
s=np.arange(animals.shape[0])
np.random.shuffle(s)
animals=animals[s]
labels=labels[s]

In [27]:
num_classes=len(np.unique(labels))
data_length=len(animals)

In [28]:
(x_train,x_test)=animals[(int)(0.1*data_length):],animals[:(int)(0.1*data_length)]
x_train = x_train.astype('float32')/255
x_test = x_test.astype('float32')/255
train_length=len(x_train)
test_length=len(x_test)

In [29]:
(y_train,y_test)=labels[(int)(0.1*data_length):],labels[:(int)(0.1*data_length)]

In [30]:
import keras
from keras.utils import np_utils
#One hot encoding
y_train=keras.utils.to_categorical(y_train,num_classes)
y_test=keras.utils.to_categorical(y_test,num_classes)

In [31]:
# import sequential model and all the required layers
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D,Dense,Flatten,Dropout
#make model
model=Sequential()
model.add(Conv2D(filters=16,kernel_size=2,padding="same",activation="relu",input_shape=(50,50,3)))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=32,kernel_size=2,padding="same",activation="relu"))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=64,kernel_size=2,padding="same",activation="relu"))
model.add(MaxPooling2D(pool_size=2))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(500,activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(4,activation="softmax"))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_7 (Conv2D)            (None, 50, 50, 16)        208       
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, 25, 25, 16)        0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 25, 25, 32)        2080      
_________________________________________________________________
max_pooling2d_8 (MaxPooling2 (None, 12, 12, 32)        0         
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 12, 12, 64)        8256      
_________________________________________________________________
max_pooling2d_9 (MaxPooling2 (None, 6, 6, 64)          0         
_________________________________________________________________
dropout_5 (Dropout)          (None, 6, 6, 64)          0         
__________

In [32]:
# compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', 
                  metrics=['accuracy'])

In [33]:
model.fit(x_train,y_train,batch_size=50
          ,epochs=100,verbose=1)

Epoch 1/100
1525/1525 [==============================] - 3s 2ms/step - loss: 1.0220 - acc: 0.5908
Epoch 2/100
1525/1525 [==============================] - 2s 1ms/step - loss: 0.8064 - acc: 0.6721
Epoch 3/100
1525/1525 [==============================] - 2s 1ms/step - loss: 0.6966 - acc: 0.6911
Epoch 4/100
1525/1525 [==============================] - 2s 1ms/step - loss: 0.6046 - acc: 0.7377
Epoch 5/100
1525/1525 [==============================] - 2s 1ms/step - loss: 0.5067 - acc: 0.7600
Epoch 6/100
1525/1525 [==============================] - 2s 1ms/step - loss: 0.4267 - acc: 0.7974
Epoch 7/100
1525/1525 [==============================] - 2s 1ms/step - loss: 0.3685 - acc: 0.8223
Epoch 8/100
1525/1525 [==============================] - 2s 1ms/step - loss: 0.3245 - acc: 0.8354
Epoch 9/100
1525/1525 [==============================] - 2s 1ms/step - loss: 0.2995 - acc: 0.8223
Epoch 10/100
1525/1525 [==============================] - 2s 1ms/step - loss: 0.2886 - acc: 0.8321
Epoch 11/100
1525/1

In [34]:
score = model.evaluate(x_test, y_test, verbose=1)
print('\n', 'Test accuracy:', score[1])

169/169 [==============================] - 0s 2ms/step

 Test accuracy: 0.7455621308828952


In [35]:
def convert_to_array(img):
    print(img)
    im = cv2.imread(img)
    print(im)
    img = Image.fromarray(im, 'RGB')
    image = img.resize((50, 50))
    return np.array(image)

def get_animal_name(label):
    if label==0:
        return "cat"
    if label==1:
        return "bat"
    if label==2:
        return "spider"
    
def predict_animal(file):
    print("Predicting .................................")
    print(file)
    ar=convert_to_array(file)
    ar=ar/255
    label=1
    a=[]
    a.append(ar)
    a=np.array(a)
    score=model.predict(a,verbose=1)
    print(score)
    label_index=np.argmax(score)
    print(label_index)
    acc=np.max(score)
    animal=get_animal_name(label_index)
    print(animal)
    print("The predicted Animal is a "+animal+" with accuracy =    "+str(acc))

In [39]:
image_path = os.path.join("C:\\Users\\win_10\\Desktop\\Final Project\\test_images\\wolverine2.jpg")
predict_animal(image_path)

Predicting .................................
C:\Users\win_10\Desktop\Final Project\test_images\wolverine2.jpg
C:\Users\win_10\Desktop\Final Project\test_images\wolverine2.jpg
[[[222 221 225]
  [222 221 225]
  [223 222 226]
  ...
  [244 244 244]
  [246 244 244]
  [247 245 245]]

 [[222 221 225]
  [223 222 226]
  [224 223 227]
  ...
  [245 244 244]
  [248 246 246]
  [248 246 246]]

 [[223 222 226]
  [224 223 227]
  [224 223 227]
  ...
  [245 245 245]
  [247 246 246]
  [248 246 246]]

 ...

 [[249 253 254]
  [249 253 254]
  [248 252 253]
  ...
  [251 250 254]
  [250 249 253]
  [251 250 254]]

 [[249 253 254]
  [249 253 254]
  [249 253 254]
  ...
  [252 251 255]
  [251 250 254]
  [251 250 254]]

 [[249 253 254]
  [249 253 254]
  [249 253 254]
  ...
  [252 251 255]
  [252 251 254]
  [251 250 254]]]
1/1 [==============================] - 0s 18ms/step
[[2.1524746e-04 4.0766108e-01 5.7748479e-01 1.4638970e-02]]
2
spider
The predicted Animal is a spider with accuracy =    0.5774848
